package es.gortizlavado.league.app.models.enums;

public enum Team {
    C_AT_PUEBLONUEVO,
    C_AT_SAN_JOSE_PROMESAS,
    CD_AZUAGA,
    CD_BADAJOZ,
    CD_CASTUERA_SUBASTACAR,
    CD_CORIA,
    CD_DITER_ZAFRA,
    CD_DON_BENITO,
    CD_HERNAN_CORTES,
    CP_SANVICENTENIO,
    CPVO_VALDIVIA,
    DEPORTIVO_PACENSE,
    EXTREMADURA_UD,
    IBERITOS_SANTA_AMALIA_CD,
    JEREZ_CF,
    MERIDA_AD,
    MORALO_CP,
    OLVENZA_FC,
    UD_FUENTE_DE_CANTOS,
    UP_PLASENCIA,
    NO_TEAM
}
